services:
    tvf_admin.crawlhandler:
        class: TVF\AdminBundle\Handler\TVFCrawlhandler
        arguments: [%img_dir%]
#    tvf_admin.example:
#        class: TVF\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
