<?php

namespace TVF\RecordBundle\Repository;

/**
 * VinylRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinylRepository extends \Doctrine\ORM\EntityRepository
{
}
