<?php

namespace TVF\RecordBundle\Repository;

/**
 * VinylRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinylRepository extends \Doctrine\ORM\EntityRepository
{
  public function search($query)
  {
    return $this->createQueryBuilder('e')
          ->innerJoin('e.artists', 'a')
          ->innerJoin('e.category', 'c')
          ->where("c.slug = 'vinyle'")
          ->andWhere('a.name LIKE :query_artist OR e.name LIKE :query')
          ->setParameter('query_artist', '%'.$query.'%')
          ->setParameter('query', '%'.$query.'%')
          ->orderBy('e.id', 'DESC')
          ->getQuery()
          ->getResult()
    ;
  }
  public function getVinyls($filters, $order, $limit=-1){
    if($limit > 0){
      $products = $this->findBy($filters, $order, $limit);
    } else {
      $products = $this->findBy($filters, $order);
    }
    $vinyls = [];
    foreach ($products as $product) {
      if($product->getCategory()->getSlug() == 'vinyle'){
        $vinyls[] = $product;
      }
    }
    return $vinyls;
  }
}
