tvf_store_work:
    path:     /work
    defaults: { _controller: TVFStoreBundle:Home:work }

# Behaviour
tvf_store_vinyl_love:
    path:     /vinyl/love/{id}
    defaults: { _controller: TVFStoreBundle:Behaviour:love, id:0 }
tvf_store_vinyl_unlove:
    path:     /vinyl/unlove/{id}
    defaults: { _controller: TVFStoreBundle:Behaviour:unlove, id:0 }
tvf_store_user_set_profile:
    path:     /user/profile
    defaults: { _controller: TVFStoreBundle:Behaviour:setProfile }

# Customer
tvf_store_customer_register:
    path:     /register
    defaults: { _controller: TVFStoreBundle:Customer:register }
tvf_store_customer_register_or_login:
    path:     /register_or_login
    defaults: { _controller: TVFStoreBundle:Customer:register_or_login }
tvf_store_cart:
    path:     /mon-panier/{embedded}
    defaults: { _controller: TVFStoreBundle:Customer:cart, embedded:0 }
tvf_store_add_to_cart:
    path:     /selectionner/{id}
    defaults: { _controller: TVFStoreBundle:Customer:addToCart, id:0 }
tvf_store_remove_from_cart:
    path:     /retirer/{id}
    defaults: { _controller: TVFStoreBundle:Customer:removeFromCart, id:0 }

# Home
tvf_store_homepage:
    path:     /
    defaults: { _controller: TVFStoreBundle:Home:homepage }
tvf_store_selection:
    path:     /selections
    defaults: { _controller: TVFStoreBundle:Home:selection }
tvf_store_history:
    path:     /histoire
    defaults: { _controller: TVFStoreBundle:Home:history }
tvf_store_contact:
    path:     /contact
    defaults: { _controller: TVFStoreBundle:Home:contact }
tvf_store_join:
    path:     /join
    defaults: { _controller: TVFStoreBundle:Home:join }

# Box
tvf_store_discover_box:
    path:     /abonnements
    defaults: { _controller: TVFStoreBundle:Box:discover }

# Search
tvf_store_search:
    path:     /search
    defaults: { _controller: TVFStoreBundle:Search:search }
tvf_store_show:
    path:     /show/{id}
    defaults: { _controller: TVFStoreBundle:Search:show, id:0 }
tvf_store_loved:
    path:     /votre-selection
    defaults: { _controller: TVFStoreBundle:Search:loved }
tvf_store_explore:
    path:     /collection/{selection}/{category}
    defaults: { _controller: TVFStoreBundle:Search:selection, selection:"_", category:"_" }
tvf_store_explore_record:
    path:     /disquaire/collection/{slug}
    defaults: { _controller: TVFStoreBundle:Search:recordCollection}
tvf_store_vinyl:
    path:     /vinyl/
    defaults: { _controller: TVFStoreBundle:Search:indexVinyls}
tvf_store_vinyl_show:
    path:     /vinyl/{id}
    defaults: { _controller: TVFStoreBundle:Search:showVinyl }
tvf_store_artist_search:
  path:     /about/{spotify_id}
  defaults: { _controller: TVFRecordBundle:Artist:Search, spotify_id: '' }
