tvf_record_client_add:
  path:     /record/client/add/{id}
  defaults: { _controller: TVFRecordBundle:Client:add, id:0 }
tvf_record_client_show:
  path:     /record/client/show/{id}
  defaults: { _controller: TVFRecordBundle:Client:show, id:0 }
tvf_record_client_token:
  path:     /record/client/get/token
  defaults: { _controller: TVFRecordBundle:Client:token }
tvf_record_my_account:
  path:     /record/mon-compte
  defaults: { _controller: TVFRecordBundle:Client:myAccount, id:0 }
tvf_record_client_present:
  path:     /disquaire/{slug}
  defaults: { _controller: TVFRecordBundle:Client:present, slug:'' }
tvf_record_selection:
    path:     /mes-selections
    defaults: { _controller: TVFRecordBundle:Client:selection }
tvf_record_collection:
    path:     /ma-collection
    defaults: { _controller: TVFRecordBundle:Client:collection }

tvf_record_artist:
  path:     /record/artist
  defaults: { _controller: TVFRecordBundle:Artist:index }
tvf_record_artist_add:
  path:     /record/artist/add/{id}
  defaults: { _controller: TVFRecordBundle:Artist:add, id:0 }
tvf_record_artist_show:
  path:     /record/artist/show/{id}
  defaults: { _controller: TVFRecordBundle:Artist:show }
tvf_record_artist_remove:
  path:     /record/artist/remove/{id}
  defaults: { _controller: TVFRecordBundle:Artist:remove, id:0 }
tvf_record_artist_search:
  path:     /record/artist/search/{spotify_id}
  defaults: { _controller: TVFRecordBundle:Artist:search, spotify_id:0 }


tvf_record_vinyl_add:
  path:     /record/vinyl/add/{id}
  defaults: { _controller: TVFRecordBundle:Vinyl:add, id:0 }
tvf_record_vinyl_remove:
  path:     /record/vinyl/remove/{id}
  defaults: { _controller: TVFRecordBundle:Vinyl:remove}
tvf_record_selection_add:
  path:     /record/selection/add/{id}
  defaults: { _controller: TVFRecordBundle:Selection:add, id:0 }
tvf_record_selection_show:
  path:     /record/selection/{id}
  defaults: { _controller: TVFRecordBundle:Selection:show }
  requirements:
      id:   \d+
tvf_record_selection_remove:
  path:     /record/selection/remove/{id}
  defaults: { _controller: TVFRecordBundle:Selection:remove}
tvf_record_vinyl_attributes:
  path:     /record/attributes/
  defaults: { _controller: TVFRecordBundle:Attribute:index}
tvf_record_vinyl_attribute_add:
  path:     /record/attributes/add/{id}/{category}
  defaults: { _controller: TVFRecordBundle:Attribute:add, id:0, category:0}
  requirements:
      id:   \d+
tvf_record_vinyl_attribute_remove:
  path:     /record/attributes/remove/{id}
  defaults: { _controller: TVFRecordBundle:Attribute:remove}
