services:
    tvf_record.slugifyhandler:
        class: TVF\RecordBundle\Handler\TVFSlugifyhandler
#    tvf_record.example:
#        class: TVF\RecordBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
