<?php

namespace TVF\AdminBundle\Repository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{
  public function whereGender($id) {
    return $this->createQueryBuilder('e')
        ->innerJoin('e.gender', 'i')
        ->where('i.id = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getResult()
    ;
  }
}
