<?php

namespace TVF\StoreBundle\Repository;

/**
 * GenderUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenderUserRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLikedGenders($user_id) {
    return $this->createQueryBuilder('e')
        ->innerJoin('e.user', 'u')
        ->innerJoin('e.gender', 'g')
        ->select('g.name')
        ->where('u.id = :id')
        ->andWhere('e.likes = :like')
        ->setParameter('id', $user_id)
        ->setParameter('like', true)
        ->orderBy('e.confidence', 'DESC')
        ->getQuery()
        ->getResult()
    ;
  }
}
