<?php

namespace TVF\StoreBundle\Repository;

/**
 * VinylUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinylUserRepository extends \Doctrine\ORM\EntityRepository
{
}
